- name: List processes by CPU usage
  hosts: all
  tasks:
  - name: List processes
    shell:
       "top -b -n 1 -o %CPU | head -20"
    register: process_info
  - debug:
       msg: "{{process_info.stdout_lines}}"
