- name: This is get-stats example
  hosts: all
  remote_user: centos
  tasks:
    - name: "try a simple local command from input"
      local_action: 'shell ls -al {{ my_dir_output }}'
      register: result

    - name: "Output test results"
      debug:
        msg: "dir contents are: {{ result.stdout }}"